ports:
    http: 80
    https: 443
    letsencrypt: 9990
    admin: 3330
paths:
    notFound: "dist/www/404.html"
apiLimits:
    duration: 1
    points: 75
secrets:
    session: "@KbnEFV*o.T*Y3FXQhk!"
    adminPassword: ""
